#!/usr/bin/env python3

import argparse

parser = argparse.ArgumentParser(description='Translate text to morse or morse to text')
parser.add_argument(
    "processString",
    help='String to process'
)
parser.add_argument(
    "--tomorse",
    "-m",
    default=False,
    action='store_true',
    help='Transform processString to morse code'
)
parser.add_argument(
    '--totext',
    '-t',
    default=False,
    action='store_true',
    help='Transform processString to text'
)
args = parser.parse_args()

outputString = ''

# Create dictionary to translate alpha -> morse
alphaDictionary = {
    '': '',
    ' ': '/',
    '/': '−..−.',
    'A': '.-',
    'B': '-...',
    'C': '-.-.',
    'D': '-..',
    'E': '.',
    'F': '..-.',
    'G': '--.',
    'H': '....',
    'I': '..',
    'J': '.---',
    'K': '-.-',
    'L': '.-..',
    'M': '--',
    'N': '-.',
    'O': '---',
    'P': '.--.',
    'Q': '--.-',
    'R': '.-.',
    'S': '...',
    'T': '-',
    'U': '..-',
    'V': '...-',
    'W': '.--',
    'X': '-..-',
    'Y': '-.--',
    'Z': '--..',
    '1': '.----',
    '2': '..---',
    '3': '...--',
    '4': '....-',
    '5': '.....',
    '6': '-....',
    '7': '--...',
    '8': '---..',
    '9': '----.',
    '0': '-----',
    '.': '.-.-.-',
    ',': '−−..−−',
    '?': '..−−..',
    "'": '.−−−−.',
    '!': '−.−.−−',
    '(': '−.−−.',
    ')': '−.−−.−',
    '&': '.−...',
    ':': '−−−...',
    ';': '−.−.−.',
    '=': '−...−',
    '+': '.−.−.',
    '-': '−....−',
    '_': '..−−.−',
    '"': '.−..−.',
    '$': '...−..−',
    '@': '.−−.−.',
    '<END OF WORK>': '...−.−',      # These won't translate alpha -> morse but will do morse -> alpha
    '<ERROR>': '........',
    '<INVITE>': '−.−',
    '<STARTING>': '−.−.−',
    '<PAGE>': '.−.−.',
    '<UNDERSTOOD>': '...−.',
    '<WAIT>': '.−...'
}

# Create dictionary to translate morse -> text based on alpha -> morse
morseDictionary = {}
for key in alphaDictionary: morseDictionary[alphaDictionary[key]] = key

processString = args.processString.upper()

if (args.tomorse == True):

    processString = list(processString)
    for letter in processString: outputString += ' ' + alphaDictionary[letter] + ' '
    outputString = outputString.replace('     ', ' / ')

elif (args.totext == True):

    processString = processString.split(' ')
    for letter in processString: outputString += morseDictionary[letter]

print(outputString.strip())
